### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by adminsend** [devon-mar/netbox-lists#27]
Is there a chance to filter based on tenant or VRF?

TNX, ciao

**Comment by devon-mar** [comment]
This plugin uses the same filters (plus some additional ones) as the builtin NetBox API endpoints. You can checkout the API documentation for this plugin by opening the API documentation on a NetBox instance with this plugin installed.

**Comment by jschewebbn** [comment]
I'm not sure about the original requestor, however I'd like to query based on tenant in much the same way you can query based on tag. Find me all IP addresses and prefixes in the specified tenant and summarize the result.

**Comment by devon-mar** [comment]
@jschewebbn could you open a new issue and explain your use case. Is there any reason why you can't just use the tenant filter on the existing endpoints?
