### ISSUE TITLE
Netbox 4.0 support

### ISSUE THREAD

**Issue by andytruett** [devon-mar/netbox-lists#58]
v3.1.1 doesn't support Netbox 4.0.

I edited netbox_lists/__init.py__ in my local copy to reflect the plugin resources relocation and the plugin works for me on 4.0.

![image](https://github.com/devon-mar/netbox-lists/assets/7491207/152345b2-ac3c-452c-96e2-7b9385e4b222)

**Comment by devon-mar** [comment]
I've published v4.0.0 to PyPi. It supports NetBox v4.0.0. 
There were a couple of other changes that I needed to make, so make sure to upgrade to the latest version.
