### ISSUE TITLE
Error on Prometheus

### ISSUE THREAD

**Issue by ginsul** [devon-mar/netbox-lists#85]
Got error using example prometheus :

ts=2024-08-17T16:52:09.052Z caller=refresh.go:99 level=error component="discovery manager scrape" discovery=http msg="Unable to refresh target groups" err="json: cannot unmarshal string into Go value of type struct { Targets []string \"json:\\\"targets\\\"\"; Labels model.LabelSet \"json:\\\"labels\\\"\" }"

  - job_name: "http_sd_combined"
    http_sd_configs:
      - url: http://172.25.30.129:8000/api/plugins/lists/devices/?tag=munculin
        refresh_interval: 15s
        authorization:
          type: "Token"
          credentials: "7d26bce8fa04deb53d0a45df25d5127b1cb4faa1"

GET api/plugins/lists/devices/?tag=munculin
{
"172.25.30.204"
}

**Comment by devon-mar** [comment]
You need to use the `prometheus-devices` endpoint instead of `devices`.
